<center><h1>Raj Panchasara</h1></center>
<center><h1>23010101185</h1></center><br>
<center><h2>Data Preprocessing</h2></center>

# Week 2 Task :

## Import library

In [1]:
import pandas as pd

## Read Data File

In [64]:
df = pd.read_csv("cardio_train.csv", sep=';')
df

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

## Give String value to gender column

In [65]:
df["gender"] = df["gender"].map({1: 'Male', 2: 'Female'})
df

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,Female,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,Male,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,Male,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,Female,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,Male,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,19240,Female,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,Male,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,Female,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,Male,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,Male,170,72.0,120,80,2,1,0,0,1,0

## Convert number of day to year in age cloumn

In [66]:
df["age"] = (df["age"]/365.25).round()
df

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,50.0,Female,168,62.0,110,80,1,1,0,0,1,0
1,1,55.0,Male,156,85.0,140,90,3,1,0,0,1,1
2,2,52.0,Male,165,64.0,130,70,3,1,0,0,0,1
3,3,48.0,Female,169,82.0,150,100,1,1,0,0,1,1
4,4,48.0,Male,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,53.0,Female,168,76.0,120,80,1,1,1,0,1,0
69996,99995,62.0,Male,158,126.0,140,90,2,2,0,0,1,1
69997,99996,52.0,Female,183,105.0,180,90,3,1,0,1,0,1
69998,99998,61.0,Male,163,72.0,135,80,1,2,0,0,0,1
69999,99999,56.0,Male,170,72.0,120,80,2,1,0,0,1,0

## Perform Dummy variable trap in gender cloumn

In [67]:
df = pd.get_dummies(df, columns=['gender'], drop_first=True, dtype=bool)
df

,id,age,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,gender_Male
0,0,50.0,168,62.0,110,80,1,1,0,0,1,0,False
1,1,55.0,156,85.0,140,90,3,1,0,0,1,1,True
2,2,52.0,165,64.0,130,70,3,1,0,0,0,1,True
3,3,48.0,169,82.0,150,100,1,1,0,0,1,1,False
4,4,48.0,156,56.0,100,60,1,1,0,0,0,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,53.0,168,76.0,120,80,1,1,1,0,1,0,False
69996,99995,62.0,158,126.0,140,90,2,2,0,0,1,1,True
69997,99996,52.0,183,105.0,180,90,3,1,0,1,0,1,False
69998,99998,61.0,163,72.0,135,80,1,2,0,0,0,1,True
69999,99999,56.0,170,72.0,120,80,2,1,0,0,1,0,True

## BMI Feature Engineering

In [68]:
df['height_m'] = df['height'] / 100
df['bmi'] = df['weight'] / (df['height_m'] ** 2)
df

,id,age,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,gender_Male,height_m,bmi
0,0,50.0,168,62.0,110,80,1,1,0,0,1,0,False,1.68,21.967120
1,1,55.0,156,85.0,140,90,3,1,0,0,1,1,True,1.56,34.927679
2,2,52.0,165,64.0,130,70,3,1,0,0,0,1,True,1.65,23.507805
3,3,48.0,169,82.0,150,100,1,1,0,0,1,1,False,1.69,28.710479
4,4,48.0,156,56.0,100,60,1,1,0,0,0,0,True,1.56,23.011177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,53.0,168,76.0,120,80,1,1,1,0,1,0,False,1.68,26.927438
69996,99995,62.0,158,126.0,140,90,2,2,0,0,1,1,True,1.58,50.472681
69997,99996,52.0,183,105.0,180,90,3,1,0,1,0,1,False,1.83,31.353579
69998,99998,61.0,163,72.0,135,80,1,2,0,0,0,1,True,1.63,27.099251
69999,99999,56.0,170,72.0,120,80,2,1,0,0,1,0,True,1.70,24.913495

## Count missing values

In [69]:
df = df.drop_duplicates()
df.shape

(70000, 15)

## Remove Duplicates

In [70]:
print(df.isnull().sum())

id             0
age            0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
gender_Male    0
height_m       0
bmi            0
dtype: int64

## Outlier Detection & Removal (IQR Method)

In [71]:
columns_to_check = ['height', 'weight', 'ap_hi', 'ap_lo']

Q1 = df[columns_to_check].quantile(0.25)
Q3 = df[columns_to_check].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

cleaned_df = df[
    ~((df[columns_to_check] < lower_bound) |
      (df[columns_to_check] > upper_bound)).any(axis=1)
]

In [72]:
print(f"Total Removed rows : {df.shape[0]-cleaned_df.shape[0]}")

Total Removed rows : 7495

## Save new Apply

In [73]:
cleaned_df.to_csv("cardio_train_clean.csv", index=False)

In [74]:
final_df = pd.read_csv("cardio_train_clean.csv")
final_df

,id,age,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,gender_Male,height_m,bmi
0,0,50.0,168,62.0,110,80,1,1,0,0,1,0,False,1.68,21.967120
1,1,55.0,156,85.0,140,90,3,1,0,0,1,1,True,1.56,34.927679
2,2,52.0,165,64.0,130,70,3,1,0,0,0,1,True,1.65,23.507805
3,3,48.0,169,82.0,150,100,1,1,0,0,1,1,False,1.69,28.710479
4,8,60.0,151,67.0,120,80,2,2,0,0,0,0,True,1.51,29.384676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62500,99991,54.0,172,70.0,130,90,1,1,0,0,1,1,True,1.72,23.661439
62501,99992,58.0,165,80.0,150,80,1,1,0,0,1,1,True,1.65,29.384757
62502,99993,53.0,168,76.0,120,80,1,1,1,0,1,0,False,1.68,26.927438
62503,99998,61.0,163,72.0,135,80,1,2,0,0,0,1,True,1.63,27.099251
62504,99999,56.0,170,72.0,120,80,2,1,0,0,1,0,True,1.70,24.913495